### ISSUE TITLE
Juroren Fotos

### ISSUE THREAD

**Issue by katjavolk** [tinkerfestival/web#11]
Über den Namen der Juroren Bilder einfügen
![juror_christian_andersen](https://user-images.githubusercontent.com/41953030/69726631-36d8eb00-1121-11ea-864c-4e9342d1d720.jpg)
![juror_erich_schoels](https://user-images.githubusercontent.com/41953030/69726632-36d8eb00-1121-11ea-8335-41ba4a0a8b63.jpg)
![juror_philipp_stollenmayer](https://user-images.githubusercontent.com/41953030/69726633-36d8eb00-1121-11ea-975b-10ead35d0695.jpg)

**Comment by kartoffelfighter** [comment]
Wer ist wer?

**Comment by katjavolk** [comment]
1. Christian Andersen
2. Erich Schöls
3. Philipp Stollenmayer
